### ISSUE TITLE
Fix Dependencies

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-safe#1]
Can't compile the safe-contracts dependency until this is fixed: https://github.com/ApeWorX/ape/issues/1221

**Comment by fubuloubu** [comment]
For now, use this: https://gist.github.com/fubuloubu/3b8daabb2918aa28496459ca50c71095

**Comment by 0xants** [comment]
Is this still an issue?

**Comment by fubuloubu** [comment]
> I am getting an error after a plugin install:
> ```
> Traceback (most recent call last):
>   File "/Users/dev/multisig/.venv/bin/ape", line 5, in <module>
>     from ape._cli import cli
>   File "/Users/dev/multisig/.venv/lib/python3.9/site-packages/ape/__init__.py", line 7, in <module>
>     from ape.managers.project import ProjectManager as Project
>   File "/Users/dev/multisig/.venv/lib/python3.9/site-packages/ape/managers/__init__.py", line 3, in <module>
>     from ape.plugins import PluginManager
>   File "/Users/dev/multisig/.venv/lib/python3.9/site-packages/ape/plugins/__init__.py", line 8, in <module>
>     from ape.exceptions import ApeAttributeError
>   File "/Users/dev/multisig/.venv/lib/python3.9/site-packages/ape/exceptions.py", line 14, in <module>
>     from ethpm_types import ContractType
>   File "/Users/dev/multisig/.venv/lib/python3.9/site-packages/ethpm_types/__init__.py", line 1, in <module>
>     from .abi import ABI
>   File "/Users/dev/multisig/.venv/lib/python3.9/site-packages/ethpm_types/abi.py", line 3, in <module>
>     from pydantic import Extra, Field
>   File "pydantic/__init__.py", line 2, in init pydantic.__init__
>   File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
>     # | <blank> | No action: no method is added.          |
> ImportError: cannot import name dataclass_transform
> ```

Can you share `pip freeze`? Maybe it's using Pydantic 2.0

**Comment by fubuloubu** [comment]
@dtdang @antazoey can you confirm this was resolved with the NPM dep work?

**Comment by dtdang** [comment]
@fubuloubu Checked and confirmed that the issue was resolved with the NPM dep feature.
