### ISSUE TITLE
supoprt delegates [APE-1156]

### ISSUE THREAD

**Issue by banteg** [ApeWorX/ape-safe#13]
### Overview

safe owners can manage delegates. delegates can submit transactions to the safe api. they sign them as ususal, but once accepted, these transactions will have 0 confirmations. delegating tx creation is useful for different automation.

### Specification

[create_delegate_message_hash](https://github.com/safe-global/safe-eth-py/blob/a0a5771622f143ee6301cfc381c5ed50832ff482/gnosis/safe/api/transaction_service_api.py#L34)
[get_delegates](https://github.com/safe-global/safe-eth-py/blob/a0a5771622f143ee6301cfc381c5ed50832ff482/gnosis/safe/api/transaction_service_api.py#L157)
[add_delegate](https://github.com/safe-global/safe-eth-py/blob/a0a5771622f143ee6301cfc381c5ed50832ff482/gnosis/safe/api/transaction_service_api.py#L175)
[remove_delegate](https://github.com/safe-global/safe-eth-py/blob/a0a5771622f143ee6301cfc381c5ed50832ff482/gnosis/safe/api/transaction_service_api.py#L196)

### Dependencies

none

**Comment by fubuloubu** [comment]
closing in favor of #16, which has more info
