### ISSUE TITLE
Multicall Bytecode is not unique

### ISSUE THREAD

**Issue by solarthesis** [ApeWorX/ape-safe#27]
### Environment information

- `ape` and plugin versions:
safe - 0.7.0b0

```
$ ape --version
# ...copy and paste result of above command here...
0.7.1

$ ape plugins list
# ...copy and paste result of above command here...
```
Installed Plugins
```
  alchemy      0.7.1
  etherscan    0.7.0
  foundry      0.7.1
  optimism     0.7.1
  safe         0.7.0b0
  solidity     0.7.1
```
- Python Version: 3.9.0
- OS: osx/linux/win: linux baby!

### What went wrong?
The bytecode of the multicall contract `0x998739BFdAAdde7C933B942a68053933098f9EDa` is not a unique identifier for the contract, optimism does not match with what is saved under the [repo](https://github.com/ApeWorX/ape-safe/blob/58fd3485dc6dd79c1d5ad9ca2b3f781f95854ebb/ape_safe/multisend.py#L11). This results in `UnsupportedChainError: Multicall not supported on this chain.` when trying to run a multicall on optimism. 

Please include information like:

- what command you ran
```
        with networks.optimism.mainnet.use_default_provider():
            contract = Contract(address=address,abi=json.loads(abi))
            txn = multisend.MultiSend()
            txn.add(contract.transfer,"0xxxxxxxxxxxxxxxx",1000000,delegatecall=True)
            txn(sender=self.safe)
```
- the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)
- full output of the error you received
`UnsupportedChainError: Multicall not supported on this chain.`

### How can it be fixed?
I would remove the check [here](https://github.com/ApeWorX/ape-safe/blob/58fd3485dc6dd79c1d5ad9ca2b3f781f95854ebb/ape_safe/multisend.py#L135) in favor of printing an output to the user in case the chain is not endorsed. Endorsed chain ids are already pre-specified [here](https://github.com/ApeWorX/ape-safe/blob/58fd3485dc6dd79c1d5ad9ca2b3f781f95854ebb/ape_safe/multisend.py#L28).

**Comment by fubuloubu** [comment]
out of curiousity, is the Safe you are using using a different version than v1.3.0?

**Comment by fubuloubu** [comment]
Actually, might be easier than that. Just have to ensure to insert the MultiSend address into the bytecode singleton check it's doing (which changes based on what the address is)

**Comment by solarthesis** [comment]
> out of curiousity, is the Safe you are using using a different version than v1.3.0?

it's 1.3.0 actually

**Comment by solarthesis** [comment]
> Actually, might be easier than that. Just have to ensure to insert the MultiSend address into the bytecode singleton check it's doing (which changes based on what the address is)

hmm fundamentally, i thought this check is about protecting against rug deployments on some unknown chain of the MultiSend. so it would be hard to tell if a transaction a user stage does not do bad things, since bad actors can hide bad code within good code to fool whatever we setup. Unless i misunderstood what you meant there. So in the situation where actors can indeed hide malisciouness in the multisend when it executes, we can should warn the user when the chain is not supported with a notification.

**Comment by fubuloubu** [comment]
> > out of curiousity, is the Safe you are using using a different version than v1.3.0?
> 
> it's 1.3.0 actually (the latest)

Confirmed! The linked PR actually addresses an issue where the deployment address is different than the typical one
